### ISSUE TITLE
Pipeline não possui testes

### ISSUE THREAD

**Issue by EijiTomonari** [Projetos-UNICAMP/voluntariapp#21]
## Descrição

O modelo de pipeline atual realiza apenas a build, mas não os testes

## Tarefas

- [x] Instalar o [Vitest](https://vitest.dev/guide/)
- [x] Criar o primeiro teste (colocar um botão na tela e testar o botão)
- [x] Incluir job de testes na pipeline

**Comment by felipe-LAS** [comment]
Todas essas tarefas foram realizadas e a descrição está na minha pull request.
